version: "3.7"
services:
  nginx:
    image: canifa/nginx:latest
    build:
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-nginx"]
    depends_on:
      - php
  php:
    image: canifa/php
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-php"]
    depends_on:
      - mysql
      - cache
      - fullpagecache
      - sessions
  mysql:
    image: percona:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db-data:/var/lib/mysql
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-mysql"]
  cache:
    image: redis:latest
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-cache"]
  fullpagecache:
    image: redis:latest
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-fpc"]
  sessions:
    image: redis:latest
    networks:
      default:
      cnf:
        aliases: ["cnf-mage-sess"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    links:
      - "mysql:mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
      #haproxy:
      #image: haproxy:1.9
      #env_file: ./dev/docker/etc/.env
networks:
  default:
    driver: bridge
  cnf:
    external:
      name: cnf
volumes:
  db-data:
