FROM nginx:latest
MAINTAINER hiepnt
RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

RUN apt-get update; apt-get install -y \
    openssl \
    && mkdir -p /etc/nginx/ssl \
    && chmod +w /etc/nginx/ssl

COPY bin/ /usr/sbin/
COPY etc/ /etc/nginx/
COPY . /var/www/html

WORKDIR /etc/nginx

EXPOSE 80 443

ENTRYPOINT ["entrypoint.sh"]

CMD ["nginx"]
